### ISSUE TITLE
调用JS出错 不知道什么原因 是需要什么环境吗?

### ISSUE THREAD

**Issue by TaroCats** [axhello/vPlayer#2]
app.min.js:4 GET http://127.0.0.1/Test/api/mp3url.php?id=35283615 500 
(Internal Server Error)
(anonymous) @ app.min.js:4
n @ app.min.js:3
t.exports @ app.min.js:4
t.exports @ app.min.js:3
(anonymous) @ app.min.js:4

这是为什么? node.js 版本4.9.3

**Comment by axhello** [comment]
@AbleCats 请问直接访问mp3url.php有json输出么？

**Comment by TaroCats** [comment]
没有  .. 不知道该如何是好

**Comment by axhello** [comment]
@AbleCats  那可能是php版本太低？ 推荐用php5.6以上的版本的 需要开启openssl模块

**Comment by TaroCats** [comment]
回去我试试

**Comment by AbleCats** [comment]
是vue的问题 现在我安装了  但是不知道是安装出错还是怎么样 我用的nmp安装的  PHP用的7 而且也开了openssl 但是app.min.js出错

**Comment by TaroCats** [comment]
已经解决 但是不知道怎么解决解析收费歌曲 0 0
